# Generated by Django 4.0.2 on 2022-02-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        ('users', '0004_socialaccount'),
        ('posts', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='workspace.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='social_accounts',
            field=models.ManyToManyField(to='users.SocialAccount'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
