# Generated by Django 4.0.2 on 2022-02-12 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contributors',
            field=models.ManyToManyField(related_name='contributing_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
