# Generated by Django 4.0.2 on 2022-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_socialaccount_name_alter_socialaccount_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='unique_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
