# Generated by Django 4.0.2 on 2022-02-19 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_socialaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=workspace.models.rename_on_upload)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_type', to='users.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
