# Generated by Django 4.0.2 on 2022-02-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_socialaccount'),
        ('workspace', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ManyToManyField(related_name='social_type', to='users.SocialAccount'),
        ),
    ]
