# Generated by Django 4.0.2 on 2022-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_socialaccount_type'),
        ('workspace', '0003_remove_post_type_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ManyToManyField(related_name='posts', to='users.SocialAccount'),
        ),
    ]
