# Generated by Django 4.0.2 on 2022-02-26 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_socialaccount_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0004_alter_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounts', models.ManyToManyField(related_name='schedules', to='users.SocialAccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workspace.category')),
                ('day', models.ManyToManyField(to='workspace.DayName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
