# Generated by Django 4.0.2 on 2022-02-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_alter_schedulepost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepost',
            name='day',
        ),
        migrations.AddField(
            model_name='schedulepost',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workspace.dayname'),
            preserve_default=False,
        ),
    ]
